
# global params
# appRevision: ""
# targetRevision: ""
# gitopsNamespace: ""
# gitRepo: ""
# disableAutoSync: "no"
# overrideTenants: "no"

# override per cluster!
ingressDomain: "cloud.ticq.org"

operators:
- name: namespace-configuration-operator
- name: descheduler
- name: vertical-pod-autoscaler
- name: keepalived-operator
- name: certmanager-operator
- name: istio-operator
- name: keepalived-operator

clusterComponents:
- name: user-sandbox
- name: keepalived-config
- name: openshift-console-plugin
- name: external-dns
  namespace: "external-dns"
- name: certmanager-config
- name: istio-config

# enable this for gitops cluster updates!
# - name: cluster-version
#   disableFinalizers: "yes" # needs this otherwise clusterversion would be deleted
