kargo:
  api:
    adminAccount:
      # password: 
      passwordHash: $2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm
      # default: admin / admin
      tokenSigningKey: iwishtowashmyirishwristwatch
    host: kargo.apps.hc02.homelab.ticq.org 
